language: cpp

os:
  - linux
  - osx

dist: trusty

compiler:
  - clang
  - gcc

env:
  global:
    - secure: "AjdrWyF4IDjdFDsuoJ4IlqnlVwp/xgkaagg175puRk71fk5fJZOEEL2JpMZSqB4/aiMGh/esVkn38805X9ehY+eE4XhPMyLx7WqR8jjHNf61T80swpfOWxgmRsL6UHD8D0JHJe57rf2Viewo96iSGMVEW4LZVzvoo53iFI9QQ8OBc73FazdRp8Hg/X8FJ1sVuF2NxIt0mXI4ojryN03bBS9RLePZr5jI8jYIaenJZoG2KB/+Za9JM4dryno137EXb78Md406RrwGDShAcnAt9hxRqwDF4XvmpC3c//EkKB45m67WUsrMkX3eL5e2Av06Q77gjej2cdwjEqx0Ie2ZMnbsFuUsREuZHRVv/j596udRFIOHPemWUN4M8kYEvODg0vd4bK0QEiXfCdysC4kFhbeesqCVf3Wui8aQx8FBS/ORgaXh0LjdPGG9LB9n9H47ZeOn3+g3r3MCWASSh58ewWKN46wChei9fAyJQf9gRxurbEbMMSgN9Z+gnnUVlT7IMX6ijDt9RJgvBo5JyuPnJgVcmxbWPAPwCWX8lWD9fc4u9Gq/lb69uM7qgaEsodHc9bHqkf1sCHu8Vav0Ejj6celeWkDZSlClYNMBTMzwgbRIvgO1Wsh472jFOl4TokLym83Zb9sLQ1nMLvl5ilAyLKWnZvIyCju1I3k0HbJgYdc="
  matrix:
    - QT=5  BREW=5
    - QT=5  BREW=ex PPA=ubuntu-sdk-team/ppa
    - QT=51 BREW=ex PPA=beineri/opt-qt511-trusty
    - QT=52 BREW=ex PPA=beineri/opt-qt521-trusty
    - QT=53 BREW=ex PPA=beineri/opt-qt532-trusty
    - QT=54 BREW=ex PPA=beineri/opt-qt542-trusty
    - QT=55 BREW=55 PPA=beineri/opt-qt551-trusty
    - QT=56 BREW=5  PPA=beineri/opt-qt562-trusty
    - QT=57 BREW=ex PPA=beineri/opt-qt571-trusty

matrix:
  allow_failures:
    - { os: osx, env: QT=55 BREW=55 PPA=beineri/opt-qt551-trusty } # https://llvm.org/bugs/show_bug.cgi?id=26396
  exclude:
    - { os: osx, env: QT=5  BREW=ex PPA=ubuntu-sdk-team/ppa      }
    - { os: osx, env: QT=51 BREW=ex PPA=beineri/opt-qt511-trusty }
    - { os: osx, env: QT=52 BREW=ex PPA=beineri/opt-qt521-trusty }
    - { os: osx, env: QT=53 BREW=ex PPA=beineri/opt-qt532-trusty }
    - { os: osx, env: QT=54 BREW=ex PPA=beineri/opt-qt542-trusty }
    - { os: osx, env: QT=57 BREW=ex PPA=beineri/opt-qt571-trusty }
    - { os: osx, env: QT=58 BREW=ex PPA=beineri/opt-qt58-trusty  }
    - { os: osx, compiler: gcc, env: QT=5  BREW=5 } # Qt 5.6 no longer supports gcc on OS X.
    - { os: osx, compiler: gcc, env: QT=56 BREW=5  PPA=beineri/opt-qt562-trusty } # Qt 5.6 no longer supports gcc on OS X.

before_install:
  - '[[ "$TRAVIS_OS_NAME" != linux || -z "$PPA" ]] || sudo add-apt-repository -y ppa:$PPA'
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy update'
  - '[ "$TRAVIS_OS_NAME" != osx   ] || brew update'

install:
  - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get -qy install cppcheck doxygen graphviz lcov'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" != */opt-* ]] || sudo apt-get -qy install qt${QT}base qt${QT}xmlpatterns'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" == */opt-* ]] || sudo apt-get -qy install qt5-qmake qtbase5-dev libqt5xmlpatterns5-dev'
  - '[ "$TRAVIS_OS_NAME" != linux ] || npm install codacy-coverage'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew install cppcheck doxygen graphviz qt$BREW'
  - '[ "$TRAVIS_OS_NAME" != osx ] || brew link --force qt$BREW'
  - qmake -v

before_script:
  - cppcheck --error-exitcode=1 --quiet .
  - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != clang++ ]] || export QMAKESPEC=linux-clang'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$CXX" != g++     ]] || export QMAKESPEC=linux-g++'
  - '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != clang++ ]] || export QMAKESPEC=macx-clang'
  - '[[ "$TRAVIS_OS_NAME" != osx   || "$CXX" != g++     ]] || export QMAKESPEC=macx-g++'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" != */opt-* ]] || . /opt/qt$QT/bin/qt$QT-env.sh'
  - '[[ "$TRAVIS_OS_NAME" != linux || "$PPA" == */opt-* ]] || export QT_SELECT=qt5'
  - mkdir -p "$TRAVIS_BUILD_DIR-build"
  - qmake -o "$TRAVIS_BUILD_DIR-build" -r -Wall -Wlogic -Wparser CONFIG+=debug_and_release "$TRAVIS_BUILD_DIR"

script:
  - make -C "$TRAVIS_BUILD_DIR-build" -j2 all
  - make -C "$TRAVIS_BUILD_DIR-build" -j2 check TESTARGS=-silent

after_success:
  - make -C "$TRAVIS_BUILD_DIR-build/test" coverage
  - curl https://codecov.io/bash > /tmp/codecov.sh
  - bash /tmp/codecov.sh -f "$TRAVIS_BUILD_DIR-build/test/release/test-tmp/coverage.info"
  - ls ~/node_modules
  - ls ~/node_modules/codacy-coverage
  - ls ~/node_modules/codacy-coverage/bin
  - cat "$TRAVIS_BUILD_DIR-build/test/release/test-tmp/coverage.info" | `npm bin`/codacy-coverage -P "$TRAVIS_BUILD_DIR"
